version: '3.5'
services:
  db:
    build: postgresql
    image: fitness_postgresql:1.0.2
    restart: always
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: root
    networks:
      - fitness_ntwrk
  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    networks:
      - fitness_ntwrk
#  minio:
#    build: minio
#    image: fitness_minio:1.0.1
#    restart: always
#    environment:
#      MINIO_ROOT_USER: minioadmin
#      MINIO_ROOT_PASSWORD: minioadmin
#    networks:
#      - fitness_ntwrk
  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk

  product-service:
    build: product-service
    image: fitness_product-service:1.0.29
    networks:
      - fitness_ntwrk
  user-service:
    build: user-service
    image: fitness_user-service:1.0.28
    networks:
      - fitness_ntwrk
  audit-service:
    build: audit-service
    image: fitness_audit-service:1.0.23
    networks:
      - fitness_ntwrk
  report-service:
    build: report-service
    image: fitness_report-service:1.0.36
    networks:
      - fitness_ntwrk

  proxy:
    build: proxy
    image: fitness_proxy:1.0.9
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk
networks:
    fitness_ntwrk:
      name: fitness_ntwrk